### ISSUE TITLE
Variance.cpp:76: unsigned int Luma8_sse2(const unsigned char*, int) [with int nBlkWidth = 4; int nBlkHeight = 4]: Assertion `0' failed.

### ISSUE THREAD

**Issue by mischa85** [pinterf/mvtools#42]
I get this when I try to use mvtools2 with AviSynth+:

`Variance.cpp:76: unsigned int Luma8_sse2(const unsigned char*, int) [with int nBlkWidth = 4; int nBlkHeight = 4]: Assertion '0' failed.`

System info:
```
System:    Host: knaagbeest Kernel: 5.12.3-arch1-1 x86_64 bits: 64 compiler: gcc v: 10.2.0 Desktop: GNOME 40.1 
           Distro: Arch Linux 
Machine:   Type: Desktop System: Gigabyte product: N/A v: N/A serial: <superuser required> 
           Mobo: Gigabyte model: Z77X-D3H v: x.x serial: <superuser required> UEFI: American Megatrends v: F18i 
           date: 01/06/2014 
CPU:       Info: Quad Core model: Intel Core i7-2600 bits: 64 type: MT MCP arch: Sandy Bridge rev: 7 L2 cache: 8 MiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 bogomips: 54476 
           Speed: 1616 MHz min/max: 1600/3800 MHz Core speeds (MHz): 1: 1616 2: 2096 3: 1602 4: 1601 5: 1602 6: 2095 7: 1646 
           8: 2557 
Graphics:  Device-1: NVIDIA TU104 [GeForce RTX 2060] driver: nvidia v: 465.27 bus ID: 01:00.0 
           Device-2: Blackmagic Design DeckLink Quad 2 driver: blackmagic-io v: 11.7a12 bus ID: 05:00.0 
           Device-3: Blackmagic Design DeckLink Quad 2 driver: blackmagic-io v: 11.7a12 bus ID: 06:00.0 
           Device-4: Conexant Systems CX23880/1/2/3 PCI Video and Audio Decoder driver: cxadc v: kernel bus ID: 0b:00.0 
           Display: x11 server: X.Org 1.20.11 driver: nvidia resolution: 1: 1920x1200 2: 1920x1200 
           OpenGL: renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2 v: 4.6.0 NVIDIA 465.27 direct render: Yes 
Network:   Device-1: Qualcomm Atheros AR8151 v2.0 Gigabit Ethernet vendor: Gigabyte driver: atl1c v: kernel port: c000 
           bus ID: 0f:00.0 
           IF: enp15s0 state: up speed: 100 Mbps duplex: full mac: 90:2b:34:34:c8:99 
Drives:    Local Storage: total: 2.55 TiB used: 2.11 TiB (82.7%) 
Info:      Processes: 284 Uptime: 10m Memory: 7.73 GiB used: 1.93 GiB (25.0%) Init: systemd Compilers: gcc: 10.2.0 
           clang: 11.1.0 Packages: 1933 Shell: Bash v: 5.1.8 inxi: 3.2.01
```

Backtrace:
```
#0  0x00007ffff5761ef5 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff574b862 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff574b747 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007ffff575a646 in  () at /usr/lib/libc.so.6
#4  0x00007fff74fe3c9a in  () at /usr/lib/avisynth/libmvtools2.so
#5  0x00007fff74fbff2f in void PlaneOfBlocks::recalculate_mv_slice<unsigned char>(MTSlicer<PlaneOfBlocks, PlaneOfBlocks, 64>::TaskData&) () at /usr/lib/avisynth/libmvtools2.so
#6  0x00007fff74dea6e4 in AvstpWrapper::fallback_enqueue_task_ptr(avstp::TaskDispatcher*, void (*)(avstp::TaskDispatcher*, void*), void*) () at /usr/lib/avisynth/libmvtools2.so
#7  0x00007fff74f88d88 in MTSlicer<PlaneOfBlocks, PlaneOfBlocks, 64>::start(int, PlaneOfBlocks&, void (PlaneOfBlocks::*)(MTSlicer<PlaneOfBlocks, PlaneOfBlocks, 64>::TaskData&), int) () at /usr/lib/avisynth/libmvtools2.so
#8  0x00007fff74f85f9e in PlaneOfBlocks::RecalculateMVs(MVClip&, MVFrame*, MVFrame*, SearchType, int, int, int, int, int, int*, short*, int, int, int, int, bool) () at /usr/lib/avisynth/libmvtools2.so
#9  0x00007fff74df7736 in GroupOfPlanes::RecalculateMVs(MVClip&, MVGroupOfFrames*, MVGroupOfFrames*, SearchType, int, int, int, int, int, int*, short*, int, int, int, bool) () at /usr/lib/avisynth/libmvtools2.so
#10 0x00007fff74f75123 in MVRecalculate::GetFrame(int, IScriptEnvironment*) () at /usr/lib/avisynth/libmvtools2.so
#11 0x00007fff8e129145 in MTGuard::GetFrame(int, IScriptEnvironment*) (this=0x7fff80324730, n=1, env=0x7fff80019a90) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/MTGuard.cpp:125
#12 0x00007fff8e15fd47 in Cache::GetFrame(int, IScriptEnvironment*) (this=0x7fff5000ab80, n=1, env_=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/cache.cpp:216
#13 0x00007fff8e160467 in CacheGuard::GetFrame(int, IScriptEnvironment*) (this=0x7fff80240230, n=1, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/cache.cpp:505
#14 0x00007fff74e4719d in MVClip::GetFrame(int, IScriptEnvironment*) () at /usr/lib/avisynth/libmvtools2.so
#15 0x00007fff74e40c8b in MVBlockFps::GetFrame(int, IScriptEnvironment*) () at /usr/lib/avisynth/libmvtools2.so
#16 0x00007fff8e129145 in MTGuard::GetFrame(int, IScriptEnvironment*) (this=0x7fff80711010, n=1, env=0x7fff80019a90) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/MTGuard.cpp:125
#17 0x00007fff8e15fd47 in Cache::GetFrame(int, IScriptEnvironment*) (this=0x7fff5000b100, n=1, env_=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/cache.cpp:216
#18 0x00007fff8e160467 in CacheGuard::GetFrame(int, IScriptEnvironment*) (this=0x7fff807de750, n=1, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/cache.cpp:505
#19 0x00007fff8e118685 in GenericVideoFilter::GetFrame(int, IScriptEnvironment*) (this=<optimized out>, n=<optimized out>, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/include/avisynth.h:1298
#20 0x00007fff8e1d439d in Trim::GetFrame(int, IScriptEnvironment*) (this=<optimized out>, n=<optimized out>, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/filters/edit.cpp:272
#21 0x00007fff8e15fd47 in Cache::GetFrame(int, IScriptEnvironment*) (this=0x7fff50883b80, n=0, env_=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/cache.cpp:216
#22 0x00007fff8e160467 in CacheGuard::GetFrame(int, IScriptEnvironment*) (this=0x7fff807de250, n=0, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/cache.cpp:505
#23 0x00007fff8e1d45cc in Splice::GetFrame(int, IScriptEnvironment*) (this=<optimized out>, n=<optimized out>, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/filters/edit.cpp:502
#24 0x00007fff8e1d45fc in Splice::GetFrame(int, IScriptEnvironment*) (this=<optimized out>, n=<optimized out>, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/filters/edit.cpp:504
#25 0x00007fff8e1d439d in Trim::GetFrame(int, IScriptEnvironment*) (this=<optimized out>, n=<optimized out>, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/filters/edit.cpp:272
#26 0x00007fff8e15fd47 in Cache::GetFrame(int, IScriptEnvironment*) (this=0x7fff3a6899b0, n=178, env_=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/cache.cpp:216
#27 0x00007fff8e160467 in CacheGuard::GetFrame(int, IScriptEnvironment*) (this=0x7fff8379a2f0, n=178, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/cache.cpp:505
#28 0x00007fff8e1d45cc in Splice::GetFrame(int, IScriptEnvironment*) (this=<optimized out>, n=<optimized out>, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/filters/edit.cpp:502
#29 0x00007fff8e1d439d in Trim::GetFrame(int, IScriptEnvironment*) (this=<optimized out>, n=<optimized out>, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/filters/edit.cpp:272
#30 0x00007fff8e15fd47 in Cache::GetFrame(int, IScriptEnvironment*) (this=0x7fff3ad54d80, n=178, env_=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/cache.cpp:216
#31 0x00007fff8e160467 in CacheGuard::GetFrame(int, IScriptEnvironment*) (this=0x7fff381c2db0, n=178, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/cache.cpp:505
#32 0x00007fff8e1d45cc in Splice::GetFrame(int, IScriptEnvironment*) (this=<optimized out>, n=<optimized out>, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/filters/edit.cpp:502
#33 0x00007fff8e1d439d in Trim::GetFrame(int, IScriptEnvironment*) (this=<optimized out>, n=<optimized out>, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/filters/edit.cpp:272
#34 0x00007fff8e15fd47 in Cache::GetFrame(int, IScriptEnvironment*) (this=0x7fff393b6ba0, n=178, env_=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/cache.cpp:216
#35 0x00007fff8e160467 in CacheGuard::GetFrame(int, IScriptEnvironment*) (this=0x7fff398cfe90, n=178, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/cache.cpp:505
#36 0x00007fff8e1d45cc in Splice::GetFrame(int, IScriptEnvironment*) (this=<optimized out>, n=<optimized out>, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/filters/edit.cpp:502
#37 0x00007fff8e1d439d in Trim::GetFrame(int, IScriptEnvironment*) (this=<optimized out>, n=<optimized out>, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/filters/edit.cpp:272
#38 0x00007fff8e15fd47 in Cache::GetFrame(int, IScriptEnvironment*) (this=0x7fff3a84b7b0, n=178, env_=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/cache.cpp:216
#39 0x00007fff8e160467 in CacheGuard::GetFrame(int, IScriptEnvironment*) (this=0x7fff3afe15c0, n=178, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/core/cache.cpp:505
#40 0x00007fff8e1d45cc in Splice::GetFrame(int, IScriptEnvironment*) (this=<optimized out>, n=<optimized out>, env=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/filters/edit.cpp:502
#41 0x00007fff8e15db70 in avs_get_frame(AVS_Clip*, int) (p=0x7fff39644840, n=<optimized out>) at /usr/src/debug/AviSynthPlus-3.7.0/avs_core/include/avisynth.h:1137
#42 0x00007ffff763b0f1 in  () at /usr/lib/libavformat.so.58
#43 0x00007ffff763b485 in  () at /usr/lib/libavformat.so.58
#44 0x00007ffff77864b2 in  () at /usr/lib/libavformat.so.58
#45 0x00007ffff7786e83 in  () at `/usr/lib/libavformat.so.58
#46 0x00007ffff7787d08 in av_read_frame () at /usr/lib/libavformat.so.58
#47 0x00005555555addfb in  ()
#48 0x00007ffff5b728d1 in  () at /usr/lib/libSDL2-2.0.so.0
#49 0x00007ffff5c11caa in  () at /usr/lib/libSDL2-2.0.so.0
#50 0x00007ffff5ada299 in start_thread () at /usr/lib/libpthread.so.0
#51 0x00007ffff5824053 in clone () at /usr/lib/libc.so.6
```

**Comment by pinterf** [comment]
Thanks. Block width 4 was not implemented for luma function in simd intrinsics. Fixed in https://github.com/pinterf/mvtools/commit/11286ea2970aab29228ea552da2ab21f5c8ad42b

**Comment by mischa85** [comment]
Brilliant. Thanks for the fix!
